spring.application.name=stokvelchain


spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

jwt.secret=${JWT_SECRET}

blockchain.rpc-url=${BLOCKCHAIN_RPC_URL:https://eth-sepolia.g.alchemy.com/v2/demo}
blockchain.contract-address=${BLOCKCHAIN_CONTRACT_ADDRESS:0xBa60BAcb8d7955EBd16d3d5B7EF5D65191eFF45c}
blockchain.wallet-private-key=${BLOCKCHAIN_WALLET_PRIVATE_KEY}

